<?xml version="1.0" encoding="utf-8"?><Database Name="Forums_System" Class="ForumSystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MATAN\MATAN;Initial Catalog=Forums_System;Integrated Security=True" SettingsObjectName="WASP.Properties.Settings" SettingsPropertyName="Forums_SystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admins" Member="IAdmins">
    <Type Name="IAdmin">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="forumId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Forum_Admin" Member="IForum" Storage="_Forum" ThisKey="forumId" OtherKey="id" Type="IForum" IsForeignKey="true" />
      <Association Name="User_Admin" Member="IUser" Storage="_User" ThisKey="userId" OtherKey="id" Type="IUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ForumMembers" Member="IForumMembers">
    <Type Name="IForumMember">
      <Column Name="forumId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Forum_ForumMember" Member="IForum" Storage="_Forum" ThisKey="forumId" OtherKey="id" Type="IForum" IsForeignKey="true" />
      <Association Name="User_ForumMember" Member="IUser" Storage="_User" ThisKey="userId" OtherKey="id" Type="IUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Forums" Member="IForums">
    <Type Name="IForum">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="subject" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Association Name="Forum_Admin" Member="IAdmins" Storage="_Admins" ThisKey="id" OtherKey="forumId" Type="IAdmin" />
      <Association Name="Forum_ForumMember" Member="IForumMembers" Storage="_ForumMembers" ThisKey="id" OtherKey="forumId" Type="IForumMember" />
      <Association Name="Forum_Post" Member="IPosts" Storage="_Posts" ThisKey="id" OtherKey="forumId" Type="IPost" />
      <Association Name="Forum_SubForum" Member="ISubForums" Storage="_SubForums" ThisKey="id" OtherKey="forumId" Type="ISubForum" />
    </Type>
  </Table>
  <Table Name="dbo.Moderators" Member="IModerators">
    <Type Name="IModerator">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="subForumId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="term" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="User_Moderator" Member="IUser" Storage="_User" ThisKey="userId" OtherKey="id" Type="IUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notifications" Member="INotifications">
    <Type Name="INotification">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fromUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="toUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="NChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="isNew" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Notification" Member="User" ThisKey="fromUserId" OtherKey="id" Type="IUser" IsForeignKey="true" />
      <Association Name="User_Notification1" Member="IUser" Storage="_User1" ThisKey="toUserId" OtherKey="id" Type="IUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Posts" Member="IPosts">
    <Type Name="IPost">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reply" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="forumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="cnt" Type="System.String" DbType="NChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="publish" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Post_Post" Member="IPosts" Storage="_Posts" ThisKey="id" OtherKey="reply" Type="IPost" />
      <Association Name="Forum_Post" Member="IForum" Storage="_Forum" ThisKey="forumId" OtherKey="id" Type="IForum" IsForeignKey="true" />
      <Association Name="Post_Post" Member="Post1" ThisKey="reply" OtherKey="id" Type="IPost" IsForeignKey="true" />
      <Association Name="User_Post" Member="IUser" Storage="_User" ThisKey="userId" OtherKey="id" Type="IUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubForums" Member="ISubForums">
    <Type Name="ISubForum">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="forumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subject" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Association Name="Forum_SubForum" Member="IForum" Storage="_Forum" ThisKey="forumId" OtherKey="id" Type="IForum" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="IUsers">
    <Type Name="IUser">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="User_Admin" Member="IAdmins" Storage="_Admins" ThisKey="id" OtherKey="userId" Type="IAdmin" />
      <Association Name="User_ForumMember" Member="IForumMembers" Storage="_ForumMembers" ThisKey="id" OtherKey="userId" Type="IForumMember" />
      <Association Name="User_Moderator" Member="IModerators" Storage="_Moderators" ThisKey="id" OtherKey="userId" Type="IModerator" />
      <Association Name="User_Notification" Member="Notifications" ThisKey="id" OtherKey="fromUserId" Type="INotification" />
      <Association Name="User_Notification1" Member="INotifications" Storage="_Notifications1" ThisKey="id" OtherKey="toUserId" Type="INotification" />
      <Association Name="User_Post" Member="IPosts" Storage="_Posts" ThisKey="id" OtherKey="userId" Type="IPost" />
    </Type>
  </Table>
</Database>